In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
import warnings
warnings.filterwarnings('ignore')
import plotly.express as px

In [3]:
df = pd.read_csv('df.csv')

df

,job_id,title,location,description,requirements,telecommuting,has_company_logo,has_questions,employment_type,required_experience,required_education,fraudulent
0,1,Marketing Intern,"US, NY, New York","Food52, a fast-growing, James Beard Award-winn...",Experience with content management systems a m...,0,1,0,Other,Internship,Bachelor's Degree,0
1,2,Customer Service - Cloud Video Production,"NZ, , Auckland",Organised - Focused - Vibrant - Awesome!Do you...,What we expect from you:Your key responsibilit...,0,1,0,Full-time,Not Applicable,Bachelor's Degree,0
2,3,Commissioning Machinery Assistant (CMA),"US, IA, Wever","Our client, located in Houston, is actively se...",Implement pre-commissioning and commissioning ...,0,1,0,Full-time,Mid-Senior level,Bachelor's Degree,0
3,4,Account Executive - Washington DC,"US, DC, Washington",THE COMPANY: ESRI – Environmental Systems Rese...,"EDUCATION: Bachelor’s or Master’s in GIS, busi...",0,1,0,Full-time,Mid-Senior level,Bachelor's Degree,0
4,5,Bill Review Manager,"US, FL, Fort Worth",JOB TITLE: Itemization Review ManagerLOCATION:...,QUALIFICATIONS:RN license in the State of Texa...,0,1,1,Full-time,Mid-Senior level,Bachelor's Degree,0
...,...,...,...,...,...,...,...,...,...,...,...,...
17875,17876,Account Director - Distribution,"CA, ON, Toronto",Just in case this is the first time you’ve vis...,To ace this role you:Will eat comprehensive St...,0,1,1,Full-time,Mid-Senior level,Bachelor's Degree,0
17876,17877,Payroll Accountant,"US, PA, Philadelphia",The Payroll Accountant will focus primarily on...,- B.A. or B.S. in Accounting- Desire to have f...,0,1,1,Full-time,Mid-Senior level,Bachelor's Degree,0
17877,17878,Project Cost Control Staff Engineer - Cost Con...,"US, TX, Houston",Experienced Project Cost Control Staff Enginee...,At least 12 years professional experience.Abil...,0,0,0,Full-time,Mid-Senior level,Bachelor's Degree,0
17878,17879,Graphic Designer,"NG, LA, Lagos",Nemsia Studios is looking for an experienced v...,1. Must be fluent in the latest versions of Co...,0,0,1,Contract,Not Applicable,Professional,0
17879,17880,Web Application Developers,"NZ, N, Wellington",Who are we?Vend is an award winning web based ...,We want to hear from you if:You have an in-dep...,0,1,1,Full-time,Mid-Senior level,Bachelor's Degree,0

In [4]:
df.isnull().sum() / len(df) * 100

job_id                 0.0
title                  0.0
location               0.0
description            0.0
requirements           0.0
telecommuting          0.0
has_company_logo       0.0
has_questions          0.0
employment_type        0.0
required_experience    0.0
required_education     0.0
fraudulent             0.0
dtype: float64

In [5]:
s = df['location']
s

0            US, NY, New York
1              NZ, , Auckland
2               US, IA, Wever
3          US, DC, Washington
4          US, FL, Fort Worth
                 ...
17875         CA, ON, Toronto
17876    US, PA, Philadelphia
17877         US, TX, Houston
17878           NG, LA, Lagos
17879       NZ, N, Wellington
Name: location, Length: 17880, dtype: object

In [6]:
df['country_code'] = df['location'].str.split(',', expand=True)[0]
df['city'] = df['location'].str.split(',', expand = True)[2]

In [7]:
df.head(10)

,job_id,title,location,description,requirements,telecommuting,has_company_logo,has_questions,employment_type,required_experience,required_education,fraudulent,country_code,city
0,1,Marketing Intern,"US, NY, New York","Food52, a fast-growing, James Beard Award-winn...",Experience with content management systems a m...,0,1,0,Other,Internship,Bachelor's Degree,0,US,New York
1,2,Customer Service - Cloud Video Production,"NZ, , Auckland",Organised - Focused - Vibrant - Awesome!Do you...,What we expect from you:Your key responsibilit...,0,1,0,Full-time,Not Applicable,Bachelor's Degree,0,NZ,Auckland
2,3,Commissioning Machinery Assistant (CMA),"US, IA, Wever","Our client, located in Houston, is actively se...",Implement pre-commissioning and commissioning ...,0,1,0,Full-time,Mid-Senior level,Bachelor's Degree,0,US,Wever
3,4,Account Executive - Washington DC,"US, DC, Washington",THE COMPANY: ESRI – Environmental Systems Rese...,"EDUCATION: Bachelor’s or Master’s in GIS, busi...",0,1,0,Full-time,Mid-Senior level,Bachelor's Degree,0,US,Washington
4,5,Bill Review Manager,"US, FL, Fort Worth",JOB TITLE: Itemization Review ManagerLOCATION:...,QUALIFICATIONS:RN license in the State of Texa...,0,1,1,Full-time,Mid-Senior level,Bachelor's Degree,0,US,Fort Worth
5,6,Accounting Clerk,"US, MD,",Job OverviewApex is an environmental consultin...,University degree required. TEFL / TESOL / CEL...,0,0,0,Full-time,Mid-Senior level,Bachelor's Degree,0,US,
6,7,Head of Content (m/f),"DE, BE, Berlin",Your Responsibilities: Manage the English-spea...,Your Know-How: ...,0,1,1,Full-time,Mid-Senior level,Master's Degree,0,DE,Berlin
7,8,Lead Guest Service Specialist,"US, CA, San Francisco",Who is Airenvy?Hey there! We are seasoned entr...,"Experience with CRM software, live chat, and p...",0,1,1,Full-time,Mid-Senior level,Bachelor's Degree,0,US,San Francisco
8,9,HP BSM SME,"US, FL, Pensacola",Implementation/Configuration/Testing/Training ...,MUST BE A US CITIZEN.An active TS/SCI clearanc...,0,1,1,Full-time,Associate,Bachelor's Degree,0,US,Pensacola
9,10,Customer Service Associate - Part Time,"US, AZ, Phoenix",The Customer Service Associate will be based i...,Minimum Requirements:Minimum of 6 months custo...,0,1,0,Part-time,Entry level,High School or equivalent,0,US,Phoenix

In [8]:
df.loc[df['city'] == ' ', 'city'] = np.nan

In [9]:
df.isnull().sum() / len(df) * 100

job_id                 0.00000
title                  0.00000
location               0.00000
description            0.00000
requirements           0.00000
telecommuting          0.00000
has_company_logo       0.00000
has_questions          0.00000
employment_type        0.00000
required_experience    0.00000
required_education     0.00000
fraudulent             0.00000
country_code           0.00000
city                   9.62528
dtype: float64

In [10]:
df.dropna(inplace = True)

In [11]:
import pycountry
len(pycountry.countries)

249

In [12]:
import pycountry

In [14]:
list_alpha_2 = [i.alpha_2 for i in list(pycountry.countries)]
def country(df):
    if df['country_code'] in list_alpha_2:
        return pycountry.countries.get(alpha_2 = df['country_code']).name
df['country_name'] = df.apply(country, axis = 1)

In [15]:
df.drop(['location', 'country_code'], axis = 1, inplace = True)

In [16]:
df.head(10)

,job_id,title,description,requirements,telecommuting,has_company_logo,has_questions,employment_type,required_experience,required_education,fraudulent,city,country_name
0,1,Marketing Intern,"Food52, a fast-growing, James Beard Award-winn...",Experience with content management systems a m...,0,1,0,Other,Internship,Bachelor's Degree,0,New York,United States
1,2,Customer Service - Cloud Video Production,Organised - Focused - Vibrant - Awesome!Do you...,What we expect from you:Your key responsibilit...,0,1,0,Full-time,Not Applicable,Bachelor's Degree,0,Auckland,New Zealand
2,3,Commissioning Machinery Assistant (CMA),"Our client, located in Houston, is actively se...",Implement pre-commissioning and commissioning ...,0,1,0,Full-time,Mid-Senior level,Bachelor's Degree,0,Wever,United States
3,4,Account Executive - Washington DC,THE COMPANY: ESRI – Environmental Systems Rese...,"EDUCATION: Bachelor’s or Master’s in GIS, busi...",0,1,0,Full-time,Mid-Senior level,Bachelor's Degree,0,Washington,United States
4,5,Bill Review Manager,JOB TITLE: Itemization Review ManagerLOCATION:...,QUALIFICATIONS:RN license in the State of Texa...,0,1,1,Full-time,Mid-Senior level,Bachelor's Degree,0,Fort Worth,United States
6,7,Head of Content (m/f),Your Responsibilities: Manage the English-spea...,Your Know-How: ...,0,1,1,Full-time,Mid-Senior level,Master's Degree,0,Berlin,Germany
7,8,Lead Guest Service Specialist,Who is Airenvy?Hey there! We are seasoned entr...,"Experience with CRM software, live chat, and p...",0,1,1,Full-time,Mid-Senior level,Bachelor's Degree,0,San Francisco,United States
8,9,HP BSM SME,Implementation/Configuration/Testing/Training ...,MUST BE A US CITIZEN.An active TS/SCI clearanc...,0,1,1,Full-time,Associate,Bachelor's Degree,0,Pensacola,United States
9,10,Customer Service Associate - Part Time,The Customer Service Associate will be based i...,Minimum Requirements:Minimum of 6 months custo...,0,1,0,Part-time,Entry level,High School or equivalent,0,Phoenix,United States
10,11,ASP.net Developer Job opportunity at United St...,Position : #URL_86fd830a95a64e2b30ceed829e63fd...,Position : #URL_86fd830a95a64e2b30ceed829e63fd...,0,0,0,Full-time,Mid-Senior level,Bachelor's Degree,0,Jersey City,United States

In [17]:
df.shape

(16159, 13)

In [18]:
df.to_csv('tableau.csv', index = True)